name: Build & Check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install pre-requisits
        run: sudo ./first_setup.sh

  build_debug:
    runs-on: ubuntu-latest

    needs: install

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake --preset debug

      - name: Build
        run: cmake --build --preset debug

      - name: clang-tidy
        run: cmake --build --preset debug -t clang-tidy
      
      - name: cppcheck
        run: cmake --build --preset debug -t cppcheck

  build_release:
    runs-on: ubuntu-latest

    needs: install

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake --preset release

      - name: Build
        run: cmake --build --preset release

      - name: clang-tidy
        run: cmake --build --preset release -t clang-tidy
      
      - name: cppcheck
        run: cmake --build --preset release -t cppcheck
