name: Build & Check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  configure:
    runs-on: ubuntu-latest
    container:
      image: danger89/cmake:latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure CMake
        run: make configure

      - name: Build
        run: make build-debug


      - name: Build
        run: make build-release

      - name: Run
        run: make run

      - name: cppcheck
        run: make cppcheck

      - name: clang-tidy
        run: make clang-tidy
      
